wandb:
  api_key: "f59f1641c244c4b01676975c59bf902da71a5e9c"
  project: "Project_PINN_for_synchronous_machine"

time : 1 # Total time to be considered
num_of_points : 1000 # To be used when defining new collocation points, num per second, e.g. 1000*1s = 5K points
modelling_method : True # Modelling approach to be followed, ddelta = omega or ddelta = omega*Omega_B
seed : 37
# SM IB v4
model:
  model_flag : "SM" #  Choose between "SM_IB" or "SM" or "SM_AVR" or "SM_AVR_GOV"
  machine_num : 1 # Set of machine parameters to be used
  init_condition_bounds : 1 # Set of initial conditions for the collocation points to be used
  sampling: "Lhs" # Choose between "Lhs" or "Linear" or "Random" for sampling the initial conditions for collocation points
  torch : True # Keep it True when training the model!
  
dataset:
  number : 5 # Number of dataset to be used 4 needs True method and 5 false
  shuffle: True # Shuffle the trajectories of the dataset # If True, the dataset will be shuffled
  split_ratio: 0.8 # Train and validation/test split ratio, the rest is splitted equally for validation/test
  validation_flag : True # Use validation set
  transform_input : "None" # Choose between "Std" or "MinMax" or "None" for input transformation
  transform_output : "None" # Choose between "Std" or "MinMax" or "None" for output transformation
  new_coll_points_flag : True # Use new collocation points or use from the dataset
  

nn: 
  type : "KAN" # Choose between "StaticNN" or "DynamicNN" or "PinnA" or "PinnB" or "PinnAA" this is the adj target one 
  hidden_layers: 1
  hidden_dim: 10
  loss_criterion : "MSELoss" # Choose between "MSELoss" or "L1Loss" or "SmoothL1Loss"
  optimizer : "Adam" #"LBFGS" # Choose between "Adam" or "SGD" or "RMSprop" or "LBFGS"
  weight_init: "xavier_normal" # Choose between "xavier_normal" or "xavier_uniform" or "kaiming_normal" or "kaiming_uniform" or "normal"
  lr: 0.001
  lr_scheduler : "No_scheduler" # Choose between "StepLR", "MultiStepLR", "ExponentialLR", "ReduceLROnPlateau", "No_scheduler"
  num_epochs: 100
  batch_size: 100
  early_stopping: True 
  early_stopping_patience: 500
  early_stopping_min_delta: 3e-6
  loss_data_weight : 1
  loss_dt_weight : 1 #e-4
  loss_pinn_weight : 1 #e-9
  update_weight_method : "Static" #"Static" # Choose between "Static", "ReLoBRaLo", "Dynamic", "Sam"

dirs:
  params_dir :  src/conf/params #${hydra:runtime.cwd}/src/conf/params
  init_conditions_dir : src/conf/initial_conditions #${hydra:runtime.cwd}/src/conf/initial_conditions
  dataset_dir : data #${hydra:runtime.cwd}/data
  model_dir : model #${hydra:runtime.cwd}/model